eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-zuul
server:
  port: 8769
zuul:
  routes:
    #服务转发:已api-a开头的转发给service-ribbon
    api-a:
      path: /api-a/**
      service-id: service-ribbon
    api-b:
      path: /api-b/**
      service-id: service-feign
