eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8761
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
    #mysql连接
  datasource:
    url: jdbc:mysql://localhost:3306/yach?allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: Yuejian@2017
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true

#mybatis集成
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml